"""
Step 3: Prepare Ligand Structures
==================================

Converts SMILES to 3D structures and PDBQT format.

Input: compounds.csv with SMILES
Output: PDBQT files in ligands/

Usage:
    python -m src.docking.step3_prepare_ligand --compounds compounds.csv
"""

import os
from pathlib import Path
from typing import Dict, List, Optional
import pandas as pd
import click

# Check for RDKit
try:
    from rdkit import Chem
    from rdkit.Chem import AllChem, Descriptors
    HAS_RDKIT = True
except ImportError:
    HAS_RDKIT = False


def smiles_to_3d(smiles: str, name: str, output_dir: Path) -> Optional[Path]:
    """
    Convert SMILES to 3D PDB file.
    
    Args:
        smiles: SMILES string
        name: Compound name
        output_dir: Output directory
        
    Returns:
        Path to PDB file or None
    """
    if not HAS_RDKIT:
        print(f"  ❌ RDKit not installed")
        return None
    
    output_dir.mkdir(parents=True, exist_ok=True)
    pdb_file = output_dir / f"{name}.pdb"
    
    if pdb_file.exists():
        print(f"  ⏭️  {name}.pdb already exists, skipping...")
        return pdb_file
    
    try:
        # Parse SMILES
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            print(f"  ❌ Failed to parse SMILES")
            return None
        
        # Add hydrogens
        mol = Chem.AddHs(mol)
        
        # Generate 3D coordinates using ETKDG
        params = AllChem.ETKDGv3()
        params.randomSeed = 42
        result = AllChem.EmbedMolecule(mol, params)
        
        if result == -1:
            # Try without ETKDG
            result = AllChem.EmbedMolecule(mol, randomSeed=42)
            if result == -1:
                print(f"  ❌ Failed to generate 3D coordinates")
                return None
        
        # Optimize with MMFF94
        try:
            AllChem.MMFFOptimizeMolecule(mol, maxIters=500)
        except:
            pass  # Continue even if optimization fails
        
        # Save as PDB
        Chem.MolToPDBFile(mol, str(pdb_file))
        
        return pdb_file
        
    except Exception as e:
        print(f"  ❌ Error: {e}")
        return None


def pdb_to_pdbqt_ligand(pdb_file: Path, pdbqt_file: Path) -> Optional[Path]:
    """
    Convert ligand PDB to PDBQT format.
    """
    import subprocess
    
    pdbqt_file.parent.mkdir(parents=True, exist_ok=True)
    
    # Try Open Babel
    try:
        result = subprocess.run(
            ['obabel', str(pdb_file), '-O', str(pdbqt_file), 
             '--partialcharge', 'gasteiger'],
            capture_output=True,
            text=True
        )
        if result.returncode == 0 and pdbqt_file.exists():
            return pdbqt_file
    except FileNotFoundError:
        pass
    
    # Fallback: simple conversion
    with open(pdb_file, 'r') as f_in, open(pdbqt_file, 'w') as f_out:
        f_out.write("REMARK  Generated by herbal-network-pharmacology\n")
        
        for line in f_in:
            if line.startswith(('ATOM', 'HETATM')):
                atom_name = line[12:16].strip()
                atom_type = atom_name[0] if atom_name else 'C'
                
                # Map to AutoDock atom types
                type_map = {
                    'C': 'C', 'N': 'N', 'O': 'O', 'S': 'S',
                    'H': 'H', 'P': 'P', 'F': 'F', 'I': 'I',
                    'B': 'Br', 'L': 'Cl'
                }
                ad_type = type_map.get(atom_type, 'C')
                
                padded = line.rstrip().ljust(70)
                f_out.write(f"{padded}  0.000 {ad_type:>2}\n")
            elif line.startswith('END'):
                f_out.write(line)
        
        f_out.write("TORSDOF 0\n")
    
    return pdbqt_file


@click.command()
@click.option('--compounds', '-c', required=True, help='CSV file with compounds')
@click.option('--output-dir', '-o', default=None, help='Output directory')
@click.option('--selected', '-s', multiple=True, help='Only prepare specific compounds')
def main(compounds: str, output_dir: str, selected: tuple):
    """Step 3: Prepare ligand structures for docking."""
    print("=" * 50)
    print("STEP 3: Prepare Ligand Structures")
    print("=" * 50)
    
    if not HAS_RDKIT:
        print("\n❌ ERROR: RDKit is required for this step!")
        print("Install with: pip install rdkit")
        return
    
    # Load compounds
    df = pd.read_csv(compounds)
    print(f"\nLoaded {len(df)} compounds from {compounds}")
    
    # Filter if specific compounds selected
    if selected:
        df = df[df['name'].isin(selected)]
        print(f"Filtered to {len(df)} selected compounds")
    
    if output_dir is None:
        output_dir = Path("data/mahkota_dewa_dn/results/docking/ligands")
    else:
        output_dir = Path(output_dir)
    
    pdb_dir = output_dir / "pdb"
    pdbqt_dir = output_dir / "pdbqt"
    
    results = []
    failed = []
    
    for _, row in df.iterrows():
        name = row['name'].replace(' ', '_').replace("'", "").replace(",", "")
        smiles = row['smiles']
        
        print(f"\n[{name}]")
        
        # Generate 3D
        pdb_file = smiles_to_3d(smiles, name, pdb_dir)
        if not pdb_file:
            failed.append(name)
            continue
        print(f"  ✅ 3D structure: {pdb_file.name}")
        
        # Convert to PDBQT
        pdbqt_file = pdbqt_dir / f"{name}.pdbqt"
        pdb_to_pdbqt_ligand(pdb_file, pdbqt_file)
        print(f"  ✅ PDBQT: {pdbqt_file.name}")
        
        results.append((name, pdb_file, pdbqt_file))
    
    # Save manifest
    manifest_file = output_dir / "ligand_manifest.txt"
    with open(manifest_file, 'w') as f:
        f.write("# Step 3: Ligand Preparation Manifest\n")
        f.write(f"# Total: {len(results)} prepared, {len(failed)} failed\n\n")
        for name, pdb_file, pdbqt_file in results:
            f.write(f"{name}\t{pdbqt_file}\n")
    
    print("\n" + "=" * 50)
    print("SUMMARY")
    print("=" * 50)
    print(f"✅ Prepared: {len(results)} ligands")
    print(f"❌ Failed: {len(failed)}")
    if failed:
        print(f"   Failed compounds: {', '.join(failed)}")
    print(f"📁 Output: {output_dir}")
    print(f"\n➡️  Next: Run step4_run_docking.py")


if __name__ == "__main__":
    main()
